In [1]:
import random
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
random.seed(100)

base = ['A','C','G','T']

rand_seqs=[]
for _ in range(3):
    sample = random.choices(base, k=5)
    seq = ''.join(sample)
    rand_seqs.append(seq)

seqs = np.array(rand_seqs)

In [3]:
seqs

array(['ACTGG', 'CTGAC', 'ATTCC'], dtype='<U5')

In [4]:
seqs.shape

(3,)

# Exercise

### 1. Extract k-mer count feature vector
- k-mer count 기반의 feature vector를 확인한다.  


In [5]:
class Kmer:
  def __init__(self):
    self.base_permutation = []
    self.k = 0
    self.encoded_bases = np.array([])

  def set_k(self):
    self.k = int(input('Insert K:') or 1)
    #self.k= input
    self.Permutate()

  def Permutate(self):
    permutation = []
    self.base_permutation = []
    self.permutate(permutation)

  def permutate(self, buf):
    for element in ['A', 'C', 'G', 'T']:
        buf.append(element)
        if len(buf) == self.k :
          self.base_permutation.append("".join(buf))
          buf.pop()
        else :
          self.permutate(buf)
          buf.pop()

  def ExtractKmer(self, feature):
    self.encoded_bases = np.array([])
    a = []
    for sequence in feature:
      kmerList = []
      b = []
      for i in range(0,len(sequence)-self.k+1,1):
        kmerList.append(sequence[i:i+self.k])
      #print(kmerList)
      for seq in self.base_permutation:
        c = kmerList.count(seq)
        b.append(c)
      #print(b)
      a.append(b)
    self.encoded_bases = np.array(a)
    #print(self.encoded_bases)

  def ReturnEncodedBases(self):
    print(self.encoded_bases)

A = Kmer()
seqs_1 = np.array(['ACTGG', 'CTGAC', 'ATTCC'])

#knum = int(input('Insert K:') or 1)
A.set_k()
A.ExtractKmer(seqs_1)

Insert K:1


In [6]:
A.encoded_bases
#print(A.base_permutation)

array([[1, 1, 2, 1],
       [1, 2, 1, 1],
       [1, 2, 0, 2]])

In [7]:
print(A.encoded_bases.shape)

(3, 4)


In [8]:
A.set_k()
#print(A.base_permutation)
A.ExtractKmer(seqs_1)
A.encoded_bases

Insert K:2


array([[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1]])

In [9]:
A.encoded_bases.shape

(3, 16)

### 2. Extract One-hot encoding feature vector
- to_categorical 참고  
https://www.tensorflow.org/api_docs/python/tf/keras/utils/to_categorical

In [10]:
from keras.utils import to_categorical

base_dict = {'A': 0, 'C': 1, 'G': 2, 'T': 3}

In [11]:
baseseq = np.array(['ACTGG', 'CTGAC', 'ATTCC'])
baseseqs = list(baseseq)
i=0
convertedseq = []
for sequence in baseseqs:
  sequence = list(sequence)
  #print(sequence)
  j=0
  for letter in sequence:
    sequence[j] = base_dict.get(letter)
    #print(letter)
    j+=1
  #print(sequence)
  convertedseq.append(sequence)
  i += 1
#convertedseq
onehot_encoded = to_categorical(convertedseq)
onehot_encoded = np.array(onehot_encoded, dtype="float32")
onehot_encoded

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]]], dtype=float32)

In [12]:
print(onehot_encoded.shape)

(3, 5, 4)
